name: UI Automation Test

on:
  push:
    branches: [ "*" ]
  workflow_dispatch: #git push 不再触发

jobs:
  test:
#    runs-on: ubuntu-latest
    runs-on: self-hosted #本地runner

    steps:
      - name: 拉代码
        uses: actions/checkout@v4

#      - name: 安装 Python
#        uses: actions/setup-python@v5
#        with:
#          python-version: '3.10'

     # 使用本地python
      - name: Use system Python
        run: python3 --version

      # 本地不需要安装
#      - name: 安装 Chrome
#        uses: browser-actions/setup-chrome@v1

      # ⭐ 关键：安装依赖
      - name: 创建虚拟环境并安装依赖
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: 运行测试
        run: |
          source venv/bin/activate
          pytest --alluredir=reports/allure-results

      # ⭐ 生成 Allure 报告
      - name: 安装 Allure
        run: |
          brew install allure

      - name: 生成 Allure 报告
        run: |
          allure generate reports/allure-results -o reports/allure-report --clean

      # ⭐ 上传报告（重点）
      - name: 上传 Allure 报告
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: reports/allure-report

      # ⭐ 上传截图
      - name: 上传截图
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: reports/screenshots
